// content/anecdotes.ts
export const anecdotes = [
  "Un trolleybus est un bus électrique alimenté par des lignes aériennes via deux perches.",
  "Un bus articulé mesure environ 18 mètres, contre environ 12 mètres pour un bus standard.",
  "Les métros sur pneus utilisent des galets latéraux pour le guidage et la stabilité.",
  "Le ‘cadencement’ désigne une fréquence régulière (par exemple : un départ toutes les 10 minutes).",
  "Un ‘intervalle’ est le temps séparant deux véhicules successifs sur une même ligne.",
  "Les portes palières en station améliorent la sécurité et la régularité.",
  "La caténaire alimente trains et trams : en courant continu ou alternatif selon les réseaux.",
  "Un aiguillage ferroviaire permet de faire passer les trains d’une voie à l’autre.",
  "Le tram-train peut circuler à la fois sur un réseau urbain et ferroviaire classique.",
  "Le BHNS combine voies dédiées, priorité aux feux et stations soignées.",
  "Les girouettes de bus indiquent la ligne et le terminus, généralement à l’avant et sur les côtés.",
  "Un ‘terminus technique’ sert à réguler l’exploitation sans accueillir de voyageurs.",
  "Un midibus (8 à 10 mètres) est utilisé lorsque la voirie est plus contrainte.",
  "La priorité aux feux des bus s’appuie sur des détecteurs embarqués ou des boucles au sol.",
  "Le retour du courant de traction se fait par le rail (ou par un deuxième fil).",
  "La bande podotactile en bord de quai sécurise les personnes malvoyantes.",
  "Les rames de tram peuvent être couplées pour augmenter la capacité.",
  "Les lignes de nuit assurent une continuité de service lorsque le métro est fermé.",
  "Un poste de commandement coordonne le trafic, les incidents et l’information voyageurs.",
  "La marche à ‘agent seul’ signifie que la conduite et les portes sont gérées par le conducteur.",
  "Les validateurs enregistrent l’usage des titres de transport et aident au calcul de charge.",
  "Les correspondances sont optimisées grâce à des temps de marche adaptés et une signalétique dédiée.",
  "Des arrêts ‘à la demande’ existent tard le soir pour rapprocher les voyageurs de leur domicile.",
  "Les dépôts regroupent l’entretien, le lavage et la recharge des véhicules.",
  "L’association RétroBus Essonne est une association de collection d’autobus anciens basée à Corbeil-Essonnes.",
  "Ce site a connu une première version expérimentale avant sa version actuelle.",
  "Cars Sœur ont été parmi les premiers exploitants à utiliser le site propre d’Évry-Courcouronnes.",
  "TC - Essonnes signifie Transports en Commun d’Essonne, et était initialement le nom d’un compte Instagram avant 2023.",
  "L’un des plus anciens Mercedes-Benz Citaro préservés en France est conservé par une association essonnienne.",
  "Le RER D traverse l’Essonne depuis le nord du département et figure parmi les lignes RER les plus chargées d’Île-de-France.",
  "Plusieurs lignes de bus relient Corbeil-Essonnes aux pôles du Val-de-Marne, notamment via Évry et la RN7.",
  "Le réseau TISSE dessert plusieurs dizaines de communes du sud de l’Essonne.",
  "Certains terminus utilisent des revêtements clairs pouvant limiter l’échauffement des surfaces en été.",
  "Les bus KVYVS (Keolis Val d’Yerres Val de Seine) exploitent plusieurs dizaines de lignes de bus dans le sud-est francilien.",
  "La RATP exploite plusieurs centaines de lignes de bus en Île-de-France.",
  "Un bus parcourt en moyenne plusieurs centaines de kilomètres par jour.",
  "Un bus urbain peut transporter l’équivalent de plusieurs dizaines de voitures en heure de pointe.",
  "Un bus peut rester en service jusqu’à 18 ou 20 heures par jour avec plusieurs conducteurs.",
  "Un bus peut effectuer plusieurs centaines d’arrêts au cours d’une seule journée.",
  "Les conducteurs peuvent changer de ligne régulièrement selon les roulements d’exploitation.",
  "Le terminus est souvent le point le plus sensible pour la régularité d’une ligne.",
  "Un retard de quelques minutes peut se répercuter sur l’ensemble d’une ligne.",
  "Les horaires sont construits à partir de temps de parcours mesurés sur le terrain.",
  "Le Mercedes-Benz Citaro est le bus urbain le plus répandu en France.",
  "Le Solaris Urbino s’est imposé depuis les années 2010 comme l’un des modèles les plus présents, notamment sur les réseaux récents et les flottes électriques.",
  "Un bus moderne consomme environ 40 L/100 km, contre plus de 55 à 60 L il y a 20 ans.",
  "Les bus modernes embarquent de nombreux calculateurs électroniques, comme les voitures.",
  "Un bus électrique est souvent plus lourd qu’un bus diesel en raison des batteries.",
  "Les bus GNV sont reconnaissables à leurs réservoirs de gaz situés sur le toit.",
  "Les bus sont généralement limités électroniquement entre 70 et 85 km/h.",
  "Le chauffage d’un bus diesel utilise souvent la chaleur du moteur.",
  "Les girouettes LED ont remplacé progressivement les rouleaux manuels à partir des années 1990.",
  "Le réseau ferroviaire français compte environ 29 000 km, dont près de 3 400 km en Île-de-France.",
  "Le RER D est mis en service au début des années 1990 et devient un axe majeur pour l’Essonne.",
  "Les métros sur pneus réduisent le bruit par rapport aux rames sur fer, selon les conditions.",
  "Le tram 7 d’Île-de-France dessert des zones qui ne disposaient pas de transport rapide auparavant.",
  "Les bus électriques réduisent fortement les émissions locales et le CO₂ par rapport au diesel.",
  "Un bus bien rempli émet moins de CO₂ par passager qu’une voiture individuelle.",
  "Le covoiturage en Essonne représente environ 4 à 7 % des déplacements.",
  "Le bruit des bus électriques à basse vitesse peut être artificiellement généré pour des raisons de sécurité.",
  "Les transports collectifs jouent un rôle clé dans l’accès à l’emploi, aux soins et aux loisirs.",
  "Transdev emploie plusieurs dizaines de milliers de personnes dans le monde et exploite des milliers de bus.",
  "Les anciens bus Renault / SAVIEM SC10 sont devenus des pièces de collection très recherchées.",
  "Certains conducteurs de bus en Essonne ont plus de 30 ans d’ancienneté et sont considérés comme des repères.",
  "Les réseaux de transport racontent l’histoire d’un territoire autant que ses monuments.",
  "Un dépôt de bus est à la fois un lieu de maintenance et un lieu de mémoire du réseau.",
  "Les péages franciliens n’existent que sur l’A14, contrairement aux autoroutes régionales.",
] as const;
