// content/anecdotes.ts
export const anecdotes = [
  "Un trolleybus est un bus électrique alimenté par lignes aériennes via deux perches.",
  "Un bus articulé mesure environ 18 mètres, contre ~12 mètres pour un bus standard.",
  "Les métros sur pneus utilisent des galets latéraux pour le guidage et la stabilité.",
  "Le ‘cadencement’ désigne une fréquence régulière (ex.: un départ toutes les 10 minutes).",
  "Un ‘intervalle’ est le temps séparant deux véhicules successifs sur une même ligne.",
  "Les portes palières en station améliorent sécurité et régularité.",
  "La caténaire alimente trains et trams : continu ou alternatif selon les réseaux.",
  "Un aiguillage ferroviaire permet de faire passer les trains d’une voie à l’autre.",
  "Le tram-train peut circuler sur réseau urbain et ferroviaire classique.",
  "Le BHNS combine voies dédiées, priorité aux feux et stations soignées.",
  "Les girouettes de bus informent ligne et terminus en façade et latéral.",
  "Un ‘terminus technique’ sert à réguler l’exploitation sans voyageurs.",
  "Un midibus (8–10 m) est utilisé là où la voirie est plus contrainte.",
  "La priorité aux feux des bus s’appuie sur détecteurs embarqués/boucles au sol.",
  "Le retour du courant de traction se fait par le rail (ou un deuxième fil).",
  "La bande podotactile en bord de quai sécurise les personnes malvoyantes.",
  "Les rames de tram peuvent être couplées pour augmenter la capacité.",
  "Les lignes de nuit assurent une continuité quand le métro est fermé.",
  "Un poste de commandement coordonne trafic, incidents et information.",
  "La marche à ‘agent seul’ signifie que conduite et portes sont gérées par le conducteur.",
  "Les validateurs enregistrent l’usage des titres et aident au calcul de charge.",
  "Les correspondances sont optimisées par des temps de marche et une signalétique dédiés.",
  "Des arrêts ‘à la demande’ existent tard le soir pour rapprocher du domicile.",
  "Les dépôts regroupent entretien, lavage et recharge des véhicules.",
  "L'Association ‘RétroBus Essonne’ est une association de collection d'autobus anciens basée à Corbeil Essonnes",
  "Ce site est conçu en deux version, la première était... originale !",
  "Cars Soeur étaient les premiers à utiliser le site propre actuel d'Evry-Courcouronnes.",
  "TC - Essonnes signifie Transports en Commun d'Essonne, et était principalement le nom de mon compte instagram. Puis j'ai mis mon prénom civil en 2023.",
  "Le Citaro 1 de l'Association RétroBus Essonne est le plus vieux Citaro préservé en France"
] as const;